from django.conf.urls.defaults import *

from pfacts003.phylofacts.models import UniProt

from pfacts003.utils.id_patterns import float_pat

# Direct to Template
urlpatterns = patterns('',
    (r'^quick_start/$', 'django.views.generic.simple.direct_to_template',
        {'template': 'phylofacts/quick_start.html'}),
    
    (r'^sequence/UniProt/$', 'pfacts003.phylofacts.views.uniprot'),
    (r'^sequence/UniProt/(?P<acc_or_ident>\w{6,12})/$', 'pfacts003.phylofacts.views.uniprot'),
    (r'^sequence/UniProt/(?P<acc_or_ident>\w{6,12})/orthologs/$', 'pfacts003.phylofacts.views.uniprot_orthology_groups'),
    (r'^genome/(?P<genome_name>[-_\w]+)/$', 'pfacts003.genome.views.genome_page'),                 
    (r'^citations/$', 'django.views.generic.simple.direct_to_template',
        {'template': 'phylofacts/citations.html'}), 
    (r'^statistics/$', 'django.views.generic.simple.direct_to_template',
        {'template': 'phylofacts/statistics.html'}),
    (r'^about_pf_pfam/$', 'django.views.generic.simple.direct_to_template',
        {'template': 'home/about_phylofacts_pfam.html'}),                       
    (r'^pfam/about/$', 'django.views.generic.simple.direct_to_template',
        {'template': 'phylofacts/pfam_about.html'}),
    (r'^new_phylogram_test/$', 'django.views.generic.simple.direct_to_template',
        {'template': 'phylofacts/new_phylogram2.html'}),
    (r'^pairwise/$', 'django.views.generic.simple.direct_to_template',
        {'template': 'phylofacts/pairwise.html'}),
    
)

urlpatterns += patterns('pfacts003.phylofacts.views',
    (r'^$', 'index'),
    (r'^tree_node_view/(?P<treenode>\d+)/$', 'treenode_view'),
    (r'^tree_node_view/(?P<treenode>\d+)/species_tree/json/$', 'treenode_species_tree_json'),
    (r'^tree_node_view/(?P<treenode>\d+)/orthoscope/$', 'treenode_orthoscope'),
    (r'^tree_node_view/(?P<treenode>\d+)/alignment/$', 'treenode_full_alignment'),
    (r'^tree_node_view/(?P<treenode>\d+)/alignment/T_(?P<threshold>\d{2})/(?P<seed_sequence_header_id>(\d+))/$', 'treenode_summary_alignment'),
    (r'^tree_node_view/(?P<id>.+)/download/tree/phyloxml/$', 'tree_node_phyloxml_tree_download'),
    (r'^tree_node_view/(?P<id>.+)/download/tree/newick/$', 'tree_node_newick_tree_download'),
    (r'^tree_node_view/(?P<id>.+)/download/masked_msa/$', 'tree_node_masked_msa_download'),
    (r'^tree_node_view/(?P<id>.+)/download/a2m_msa/$', 'tree_node_a2m_msa_download'),
    (r'^tree_node_view/(?P<id>.+)/download/hmm/$', 'tree_node_hmm_download'),
    (r'^tree_node_view/(?P<id>.+)/download/members/$', 'tree_node_members_download'),
    (r'^fatcat_family/(?P<id>.+)/orthoscope/$', 'fatcat_treenode_orthoscope'),
    (r'^family/$', 'family'),
    (r'^family/(?P<family_accession>bpg\d{7})/$', 'family', {}, 'family'),
    (r'^family/(?P<family_accession>bpg\d{7})/consensus/$', 'consensus'),
    (r'^family/(?P<family_accession>bpg\d{7})/seed/$', 'seed'),
    (r'^family/(?P<family_accession>bpg\d{7})/alignment/$', 'alignment'),
    (r'^family/(?P<family_accession>bpg\d{7})/tree/ml/$', 'ml_tree'),
    (r'^family/(?P<family_accession>bpg\d{7})/tree/ml/summary_T(?P<threshold>%s).json$' % float_pat, 'ml_summary_tree_json'),
    (r'^family/(?P<family_accession>bpg\d{7})/tree/nj/$', 'nj_tree'),
    (r'^family/(?P<family_accession>bpg\d{7})/tree/nj/summary_T(?P<threshold>T%s).json$' % float_pat, 'nj_summary_tree_json'),
    (r'^family/(?P<family_accession>bpg\d{7})/tree/$', 'tree'),
    (r'^family/(?P<family_accession>bpg\d{7})/tree/family/summary_T(?P<threshold>T%s).json$' % float_pat, 'family_summary_tree_json'),
    (r'^family/(?P<family_accession>bpg\d{7})/hmm/SAM/$', 'sam_hmm'),
    (r'^family/(?P<family_accession>bpg\d{7})/hmm/HMMER3/$', 'hmmer3_hmm'),
    (r'^family/(?P<family_accession>bpg\d{7})/sequences/$', 'family_sequences'),
    (r'^family/(?P<family_accession>bpg\d{7})/summary/$', 'family_summary_data'),
    (r'^family/(?P<family_accession>bpg\d{7})/phog_data/$', 'family_phog_data'),
    (r'^family/(?P<family_accession>bpg\d{7})/sequence_data/$', 'sequence_data'),
    (r'^family/(?P<family_accession>bpg\d{7})/sequence_data/(?P<page>\d+)/$', 'sequence_data'),
    (r'^family/(?P<family_accession>bpg\d{7})/phog_table/$', 'family_phog_table'),

    # TODO: why is accession_id used here instead of family_accession? - ST
    (r'^family/(?P<accession_id>bpg\d{7})/download/(?P<component>.*)', 'download'),
    (r'^search/sequence/results/(?P<id>(\w+))','sequence_search_results'),
    (r'^downloads/$', 'downloads'),
    (r'^search/$', 'search'),
    (r'^search/accession/$', 'accession_search', {}),
    (r'^query/sequence/$', 'sequence_query', {}),
    (r'^alignment/$', 'alignment_hmm_pairwise'),
    (r'^archaeopteryx_config/$', 'archaeopteryx_config'),
    (r'^coverage/$', 'coverage'),
    (r'^pfam/(?P<pfam_accession>(\w+))/','pfam'),
    (r'^biocyc_rxn/(?P<biocyc_reaction_id>(\S+))/','biocyc_reaction'),                        
    (r'^pdb/(?P<pdb_id>.+)/$', 'serve_pdb'),
    (r'^pdb/(?P<pdb_id>.+)/jmol$', 'pdb_jmol'),
    (r'^fatcat/$', 'fatcat'),
    (r'^fatcat/(?P<id>(\d+))/$', 'fatcat_job_new'),
    (r'^fatcat/about/(?P<stage_number>(\.+))/$', 'fatcat_about_detail'),
    (r'^fatcat/about/$', 'fatcat_about'),
    (r'^fatcat/supplementary/$', 'fatcat_supplementary'),
    (r'^fatcat/precalc/$', 'fatcat_precalc'),
    (r'^fatcat/help/$', 'fatcat_help'),
    (r'^fatcat/faq/$', 'fatcat_faq'),
    (r'^fatcat/example1/', 'fatcat_example_one'),
    (r'^fatcat/example2/', 'fatcat_example_two'),
    (r'^fatcat_family/(?P<family_id>(\d+))/tree/$', 'fatcat_family_tree'),                                                
    (r'^fatcat_family/(?P<family_id>(\d+))/orthoscope/$', 'fatcat_family_orthoscope'),                                                
    (r'^fatcat_family/(?P<family_id>(\d+))/$', 'fatcat_family'),
    (r'^fatcat/(?P<id>(\d+))/orthologs/', 'fatcat_orthologs'),
    (r'^fatcat/benchmarking.pdf', 'benchmarking_pdf'),
    (r'^fatcat/tutorial/', 'tutorial_pdf'),
    (r'^FSP/$', 'functional_site_prediction'),
    (r'^FSP/(?P<jobID>(\d+))/$', 'functional_site_prediction_job'),
    (r'^FSP/results/(?P<jobID>(\d+))/$', 'functional_site_prediction_job_results'),
    (r'^FSP/results/(?P<jobID>(\d+))/summary_msa/$', 'functional_site_prediction_summary_msa'),
    (r'^FSP/results/(?P<jobID>(\d+))/summary_tree/$', 'functional_site_prediction_summary_tree'),
    (r'^FSP/results/(?P<jobID>(\d+))/full_msa/$', 'functional_site_prediction_full_msa'),
    (r'^FSP/results/(?P<jobID>(\d+))/full_tree/$', 'functional_site_prediction_full_tree'),
    (r'^FSP/results/(?P<jobID>(\d+))/hmm/$', 'functional_site_prediction_hmm'),
    (r'^FSP/results/(?P<jobID>(\d+))/intrepid_rank/$', 'functional_site_prediction_intrepid_rank'),
    (r'^FSP/results/(?P<jobID>(\d+))/intrepid_score/$', 'functional_site_prediction_intrepid_score'),
    (r'^tree_node/(?P<id>.+)/$', 'tree_node'),
    (r'^tree_node/(?P<id>.+)/tree$', 'tree_node_tree'),
    (r'^view/(?P<id>.+)/phyloscope/$','new_phyloscope'),                    
    (r'^queue_table/$','queue_table'),                    
    (r'^queue/status/$','queue_status'),                    
    (r'^queue/jobs/all/$','ohana_all_jobs_table'),
    (r'^makana/admin/$', 'makana_admin'),
    (r'^login/$','phylofacts_login'),
    (r'^user_create/$','phylofacts_create_user'),                    
    (r'^my_phylofacts/$','my_phylofacts_view'),
    (r'^password_reset/$','phylofacts_password_reset'),
)

# testing section
from django.conf import settings
if settings.DEBUG is True:
    from pfacts003.phylofacts.models import Family
    urlpatterns += patterns('pfacts003.phylofacts.views',
      #(r'^sequence/(?P<sequence_type>.*)/(?P<identifier>.*)/$', 'sequence'),
      (r'^family/structure', 'structure'),
      (r'^tree/(\d+)/$', 'viewtree'),
    )
    urlpatterns += patterns('',
        #(r'^family/$', 'django.views.generic.list_detail.object_list', {'queryset': Family.objects.all(), 'paginate_by' :200}),
        #(r'^help/$', 'django.views.generic.simple.direct_to_template',
        #    {'template': 'phylofacts/help.html'}),
        #(r'^family/bpg(?P<object_id>\d{7})/$', 'django.views.generic.list_detail.object_detail', {'queryset': Family.objects.all()}, 'families'),
        #(r'^sequence/$', 'django.views.generic.list_detail.object_list', {'queryset': SequenceHeader.objects.all(), 'paginate_by': 200}),
        (r'^sequence/$', 'django.views.generic.simple.redirect_to',
            {'url': '/phylofacts/sequence/UniProt/'}),
        (r'^sequence/UniProt/$', 'django.views.generic.list_detail.object_list',
            {'queryset': UniProt.objects.all().only('uniprot_identifier'),
             'paginate_by': 200}),
        (r'^sequence/UniProt/(?P<acc_or_ident>\w{6,12})$',
            'django.views.generic.simple.redirect_to',
            {'url': '/phylofacts/sequence/UniProt/%(acc_or_ident)s/'}),
        (r'^sequence/UniProt/(?P<acc_or_ident>\w{6,12})/phogs/$',
            'pfacts003.phylofacts.views.uniprot_phogs'),
        (r'^sequence/UniProt/(?P<acc_or_ident>\w{6,12})/orthologs/$',
            'pfacts003.phylofacts.views.uniprot_orthologs'),
    )
