$(document).ready(function() {
    $('#submission_form').submit(function () {
        var msg = "";
        var blank_re = /^\s*$/;
        var textblank = blank_re.test(this.satchmo_fasta_fasta_text.value);
        var fileblank = blank_re.test(this.satchmo_fasta_fasta_file.value);
        var captblank = blank_re.test(this.recaptcha_response_field.value);
        var no_nt = this.satchmo_fasta_fasta_text.value.replace(/[\n\r]+/g,"\n").replace(/>[^\n]+\n/g,"").replace(/\s/g,"").toUpperCase().replace(/[ATCGU\n]/g,'');
        if (captblank) {
            msg += "Please populate the reCAPTCHA field.\n";
            this.recaptcha_response_field.focus();
        }
        if (!textblank && !fileblank) {
            //msg += "Please submit EITHER text input OR a file, not both.\n";
            msg += "Please submit text input.\n";
            this.satchmo_fasta_fasta_text.focus();
        } else if (textblank && fileblank) {
            msg += "Please submit either text input or a file.\n";
        } else if (!textblank && blank_re.test(no_nt)) {
            msg += "Submission appears to be nucleotide sequences; only protein seqeunces are accepted.";
        }

        /*if (blank_re.test(this.email_to.value)) {
            msg += "Please provide an email address (for notification of job completion).\n";
        }
        if (blank_re.test(this.email_subject.value)) {
            this.email_subject.value = "BPG SATCHMO Results";
        }*/
        if (!blank_re.test(msg)) {
            alert(msg);
            return false;
        }

        var bad_header = /^>.*?[\(\)]/m;
        if (bad_header.test(this.satchmo_fasta_fasta_text.value)) {
            this.satchmo_fasta_fasta_text.value = this.satchmo_fasta_fasta_text.value.replace(/\(/g,'%28').replace(/\)/g, '%29').replace(/:/g,'%3A').replace(/;/g,'%3B').replace(/\[/g,'%5B').replace(/\]/g,'%5D').replace(/,/g,'%2C');
            alert('Note: characters \'(\', \')\', \'[\', \']\', \';\', \':\', and \',\' were replaced with %28, %29, %5B, %5D, %3B, %3A, and %2C, respectively; these characters must be replaced to conform with most implementations of the Newick Tree Format.');
        }
    }).find('.example').click(function() {
        f = $(this).closest('form')[0];
        f.satchmo_fasta_fasta_text.value = ">gi|18104157|emb|CAD20463.1| globin-like ES protein F6 [Ostertagia ostertagi]\nRAASTAFVSSMGPEDVKKNSLAALESVALGTTPEKVQNGKDFYKYLFTEHPDVCKYFKGAESFTADDVQK\nSDRFAVQGMALLTSVHILADTYDNEMIFRAFVRDLMNRHKERGLDPKLWKEFWDIFEKFLESRKPLTA\n>gi|1707910|sp|P51535.1|GLB2_NIPBR RecName: Full=Myoglobin; AltName: Full=Globin, body wall isoform\nMADVKKNCLASLSLAPISKAQQAQVGKDFYKFFFTNHPDLRKYFKGAENFTADDVQKSDRFEKLGSGLLL\nSVHILANTFDNEDVFRAFCRETIDRHVGRGLDPALWKAFWSVWVAFLESKGGVSGDQKAAWDKLGTVFND\nECQHQLAKHGLPHL\n>gi|1707914|sp|P51536.1|GLBC_NIPBR RecName: Full=Globin, cuticular isoform; Flags: Precursor\nMLWFVAVCFAIASVSAMSPADVKKHTVESMKAVPVGRDKAQNGIDFYKFFFTHHKDLRKFFKGAENFGAD\nDVQKSKRFEKQGTALLLAVHVLANVYDNQAVFHGFVRELMNRHEKRGVDPKLWKIFFDDVWVPFLESKGA\nKLSGDAKAAWKELNKNFNSEAQHQLEKLGLPHA\n>gi|170593605|ref|XP_001901554.1| Globin family protein [Brugia malayi]\nMSRLVIKAKCMKVLNEAGRVGTDDEAIQHGKNFYKFMFGHHPDLRVFFKGAENFTPADVQNSDRFAKQGN\nKNSSLILYFLNRQKLLLAVRIIINTYDDPETFRAYARETINRHIKFKIDRALWLAFFTVLVNSLKEHTII\nDEEAEKAFLQIGKEFSDECLKHIIALNLCN\n>gi|25143894|ref|NP_498974.2| GLoBin family member (glb-1) [Caenorhabditis elegans]\nMSMNRQEISDLCVKSLEGRMVGTEAQNIENGNAFYRYFFTNFPDLRVYFKGAEKYTADDVKKSERFDKQG\nQRILLACHLLANVYTNEEVFKGYVRETINRHRIYKMDPALWMAFFTVFTGYLESVGCLNDQQKAAWMALG\nKEFNAESQTHLKNSNLPHV\n>gi|268574956|ref|XP_002642457.1| C. briggsae CBR-GLB-1 protein [Caenorhabditis briggsae]\nMSMTRQEIQDLCVKSLEEKMVGTTDKGIANGNGFYQYFFTNFPDLRVYFKGAEKFTAEDVKKSERFDKQG\nQRILLACHLIANVFTNEEVFKAYVRETINRHRIYKMDPALWMAFFTVFTGYLESTGSLNDQQKAAWMALG\nKEFNAECQVHLKNSNLPYVH\n>gi|1203915|gb|AAA89170.1| globin [Caenorhabditis remanei]\nMSMSRQEIQDLCVKSLEEKMVGTEAKNVDNGNGFYQYFFTNFPDLRVYFKGAEKYTAEDVKKSERFDKQG\nQRILLACHLIANVYTNEEVFKAYVRETVNRHRIYKMDPALWMAFFTVFTGYLGSTGSLTDQQKAAWMALG\nKEFNAECQEHLKNSNLPYVH\n>gi|18029241|gb|AAL56427.1|AF370722_1 intracellular globin [Syngamus trachea]\nMLTPCEVKKHVKNSLEYAPIGKTPEEIQNGKDFYKHMFTHHPDLRRYFKGAESFTADDVQKSERFEKQGQ\nRILLAVYILADTFDDEQTFRAYARETVNRHRQFKMDPSLWSAFFTVFVNFLETRGSLTDDQKKAWAQLCK\nVFDEECQSHLKTLGLPHC\n>gi|18029243|gb|AAL56428.1|AF370723_1 intracellular globin [Toxocara canis]\nMATACLKSLESAQCGTCDKAIENGTGFYALLFDKHPELRHYFKGNENLTGAEVKKSEHFKKQGQTLLLAC\nHVLAHLENDPSSFNAYCREIIDRHLRANVHLDPKLWTAFWPIWLDYLATKTTVDDATKNAWLALGKKFAD\nECCNHLKNSGQPH\n>gi|18087056|gb|AAL58704.1| hemoglobin [Toxocara canis]\nRELCMKSLKDVHVGTGDHAKQCGIDLYKHMFEHYPDLRKFFKNRENYTAEDVQKDEFFAKQGQKILLACH\nVLCATVDDMETFNAYSHEVLDRHERDHVELPASAWTVSAFIFIEYLEKKMTVDEATKNAWMEIGKDFATA\nVGQHES\n>gi|18087054|gb|AAL58703.1| hemoglobin [Toxocara canis]\nRELCMKSLKDVHVGTGDHAKQCGIDLYKHMFEHYPDLRKFFKNRENYTAEDVQKDEFFAKQGQKILLACH\nVLCATVDDMETFNAYSHEVLDRHERDHVELPASAWTVFFSIFIEYLEKKMTVDEATKNAWMEIGKDFATA\nVGQHES\n>gi|18029249|gb|AAL56430.1|AF370726_1 pseudocoelomic globin [Toxocara canis]\nMRSFALFAFALVLATVSAETKRELCMKSLKDVHVGTGDHAKQCGIDLYKHMFEHYPDLRKFFKNRENYTA\nEDVQKDEFFAKQGQKILLACHVLCATVDDMETFNAYSHEVLDRHERDHVELPASAWTDFWKIFIEYLEKK\nMTVDEATKNAWMEIGKDFATAVGQHESSHSH\n>gi|157830059|pdb|1ASH|A Chain A, The Structure Of Ascaris Hemoglobin Domain I At 2.2 Angstroms Resolution: Molecular Features Of Oxygen Avidity\nANKTRELCMKSLEHAKVDTSNEARQDGIDLYKHMFENYPPLRKYFKSREEYTAEDVQNDPFFAKQGQKIL\nLACHVLCATYDDRETFNAYTRELLDRHARDHVHMPPEVWTDFWKLFEEYLGKKTTLDEPTKQAWHEIGRE\nFAKEINKHGR\n>gi|417051|sp|P28316.2|GLB_ASCSU RecName: Full=Extracellular globin; Flags: Precursor\nMRSLLLLSIVFFVVTVSANKTRELCMKSLEHAKVDTSNEARQDGIDLYKHMFENYPPLRKYFKNREEYTA\nEDVQNDPFFAKQGQKILLACHVLCATYDDRETFNAYTRELLDRHARDHVHMPPEVWTDFWKLFEEYLGKK\nTTLDEPTKQAWHEIGREFAKEINKHGRHAVRHQCMRSLQHIDIGHSETAKQNGIDLYKHMFENYPSMREA\nFKDRENYTAEDVQKDPFFVKQGQRILLACHLLCASYDDEETFHMYVHELMERHERLGVQLPDQHWTDFWK\nLFEEFLEKKSHLCEHTKHAWAVIGKEFAYEATRHGKEHHEHKEEHKEEHKEEHKEEQH\n>gi|121273|sp|P26914.1|GLB_PSEDC RecName: Full=Extracellular globin; Flags: Precursor\nMHSSIVLAIVLFVAIASASKTRELCMKSLEHAKVGTSKEAKQDGIDLYKHMFEHYPAMKKYFKHRENYTP\nADVQKDPFFIKQGQNILLACHVLCATYDDRETFDAYVGELMARHERDHVKIPNDVWNHFWEHFIEFLGSK\nTTLDEPTKHAWQEIGKEFSHEISHHGRHSVRDHCMNSLEYIAIGDKEHQKQNGIDLYKHMFEHYPHMRKA\nFKGRENFTKEDVQKDAFFVKQGHKILLALRMLCSSYDDEPTFDYFVDALMDRHIKDDIHLPQEQWHEFWK\nLFAEYLNEKSHQHLTEAEKHAWSTIGEDFAHEADKHAKAEKDHHEGEHKEEHH\n>gi|9816|emb|CAA77743.1| hemoglobin [Pseudoterranova decipiens]\nMHSSIVLATVLFVAIASASKTRELCMKSLEHAKVGTSKEAKQDGIDLYKHMFEHYPAMKKYFKHRENYTP\nADVQKDPFFIKQGQNILLACHVLCATYDDRETFDAYVGELMARHERDHVKIPNDVWNHFWEHFIEFLGSK\nTTLDEPTKHAWQEIGKEFSHEISHHGRHSVRDHCMNSLEYIAIGDKEHQKQNGIDLYKHMFEHYPHMRKA\nFKGRENFTKEDVQKDAFFVKQGHKILLALRMLCSSYDDEPTFDYFVDALMDRHIKDDIHLPQEQWHEFWK\nLFAEYLNEKSHQHLTEAEKHAWSTIGEDFAHEADKHAKAEKDHHEGEHKEEHH\n>gi|18029239|gb|AAL56426.1|AF370721_1 cuticle globin [Syngamus trachea]\nMSSQLAPTTFFAFLFLACLSAVQVSGMAAADVKKHVVDSLVNVPLGNDQTGKDFYKYFFTNHPDLRKYFK\nGFETFTADDVQKSEKFRTLGNAFILAIHIVANTYDNEPVFRAYVRDNIARHVERGLEPSLWKDFWKIWTA\nFLESKGTTLSADDKAAWEALRDRFNDESQKELAKRGLPHA\n>gi|160797|gb|AAA29796.1| hemoglobin [Pseudoterranova decipiens]\nMHSSIVLATVLFVAIASASKTRELCMKSLEHAKVGTSKEAKQDGIDLYKHMFEHYPAMKKYFKHRENYTP\nADVQKDPFFIKQGQNILLACHVLCATYDDRETFDAYVGELMARHERDHVKVPNDVWNHFWEHFIEFLGSK\nTTLDEPTKHAWQEIGKEFSHEISHHGRHSVRDHCMNSLEYIAIGDKEHQKQNGIDLYKHMFEHYPHMRKA\nFKGRENFTKEDVQKDAFFVNKDTRFCWPFVCCDSSYDDEPTFDYFVDALMDRHIKDDIHLPQEQWHEFWK\nLFAEYLNEKSHQHLTEAEKHAWSTIGEDFAHEADKHAKAEKDHHEGEHKEEHH\n";
        $(f).submit();
        return false;
    });
});

